### ISSUE TITLE
Error accepting offer

### ISSUE THREAD

**Issue by wascript3r** [bulgakovk/steamBot#14]
I try to accept trade offer but i get this error:
[10:56:12:952] Message: "Error (8)" at row:231, Content:  { [Error: There was an error accepting this trade offer.  Please try again later. (11)] eresult: 11 }

my code:
offer.accept(function(err) {
    if (err) helper.log("Error (8)", 231, err);
});

**Comment by andrewda** [comment]
Error 11 _usually_ means that the trade was actually accepted successfully, and Steam is just being dumb about it. You should probably check the status of the trade and see if it accepted successfully when you get this error.
