### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by wascript3r** [bulgakovk/steamBot#16]
Hey, i get this error when i try to send trade offer. My code:
        manager.loadInventory("730", "2", true, function(err,inventory, currencies){
            if (err) console.log(err);
            var Item;
            inventory.forEach(function(item,i,arr){
                if (item.market_hash_name == "Chroma 2 Case") Item = item;
            });
            var offer = manager.createOffer("xxxxxxxx"); //Put here stemdId
            offer.addMyItem(Item);
            offer.send("Hello!", function(err,status){
                if (err) console.log(err);
                else console.log(status);
            });
        });

**Comment by bulgakovk** [comment]
Can you show error log in console? Make screen please.

**Comment by wascript3r** [comment]
http://prntscr.com/9hc923

**Comment by bulgakovk** [comment]
Did you try to write Item in console and check it? I mean are you sure that it's correct?

**Comment by wascript3r** [comment]
I think it's because i didn't set accessToken. In other bot (it is not working now because of steam update) i see the code:

					offers.makeOffer ({
						partnerSteamId: row[i].userid,
						itemsFromMe: item,
						accessToken: row[i].token,
						itemsFromThem: [],
						message: 'Your winning on site '+sitename+' in game #'+gamenum
					}, function(err, response){
						if (err) {
							return;
						}
						console.log('Trade offer for queue '+gamenum+' sent!');	
					});

but i cannot imagine how the code should look in your bot.
