### ISSUE TITLE
How to get the authcode

### ISSUE THREAD

**Issue by hach3** [bulgakovk/steamBot#19]
Hi there,

I want to connect to steamcommunity with my bot account, is there a way to obtain the auth code that we normaly receive on the android application ?

**Comment by bulgakovk** [comment]
You can enable mobile authentication by using 2FA.js. It creates file with "shared" and "identity" secrets strings. Then you can use "steam-totp" module to generate auth codes using those secrets.

**Comment by hach3** [comment]
Created this function : 
    var timmy = SteamTotp.getConfirmationKey('secret key');
    console.log(timmy);

It doesn't return any auth code, just one more huge key. Sorry if i'm a noob :s

**Comment by bulgakovk** [comment]
Did you put your shared_secret from text file which was created after using 2FA.js as argument of function "getConfirmation"?

**Comment by hach3** [comment]
http://www.hostingpics.net/viewer.php?id=685283timmy.png Here is a screenshot, i tried with identity secret, then with shared_secret

**Comment by bulgakovk** [comment]
Did you call this function? :)

**Comment by hach3** [comment]
sure ^^ It created this key : cGp3H4a4uoudin0wBB9XXXXXXeCXA=

**Comment by hach3** [comment]
Ok you rock :) Thx again
