### ISSUE TITLE
Error 2

### ISSUE THREAD

**Issue by kafelshy** [bulgakovk/steamBot#27]
Hello!

I have problem.
I have Error 2. 
What I have to do?

**Comment by bulgakovk** [comment]
What script are you using? Can you upload screenshot?

**Comment by kafelshy** [comment]
I'm using by ClockRide - TwoFactorMade

![error2](https://cloud.githubusercontent.com/assets/16568426/12143719/43e563ae-b483-11e5-9184-d9ab41a1223b.jpg)

Here is instruction : http://pastebin.com/L0tkNQMU
I stopped on Third step and 5. Start bot.
I don't know which line I have to copy to sharedKey from saved_response.txt

You are my last hope!

**Comment by bulgakovk** [comment]
Can I see "escrow.js" sources? It's not my script, am I right? 
P.S. Can I use this instruction to make READ.ME? ;)

**Comment by kafelshy** [comment]
Can you text with my on private message? skype or smth?

**Comment by bulgakovk** [comment]
@bulgakovk on https://www.telegram.org/
