### ISSUE TITLE
add escrow to mongodb

### ISSUE THREAD

**Issue by KamyczeQ2** [bulgakovk/steamBot#32]
Hello can you help in added to escrow bot for mongodb ? I pay u

**Comment by andrewda** [comment]
It's really not that hard to implement. If you want, you can add me at steamcommunity.com/id/ChoopsMLG

**Comment by KamyczeQ2** [comment]
Can u add me escrow ? http://pastebin.com/fAhHp6zQ

**Comment by andrewda** [comment]
You can add me. I don't know your Steam link :P

**Comment by KamyczeQ2** [comment]
https://steamcommunity.com/id/enntv my steam prof
