### ISSUE TITLE
Need help with Installation 

### ISSUE THREAD

**Issue by White1337** [bulgakovk/steamBot#6]
Hey^^ im new to Steam API / Steam bots and all that stuff, i would need a bit help, since the new update im completly brainfucked, would be nice :). Do you got steam or skype or teamspeak?

**Comment by datamann10** [comment]
"The best way to learn is to try it yourself" -Me, a few months ago.

**Comment by White1337** [comment]
hmm, already did this, but i srsly dont understand it :x would be nice if someone could help me

**Comment by bulgakovk** [comment]
Actually you can ask your questions here.

**Comment by White1337** [comment]
Well, my question is how to install this / where i need to run it and all that stuff ^^

**Comment by bulgakovk** [comment]
You should to install: 
1) node.js
2) all packages from READ.ME using npm
3) enable 2FA auth using 2FA.js (you need to already have the steam account with attached phone number)

And finally just run bot.js

**Comment by White1337** [comment]
I want to install it on my Linux VPS is this possible?

**Comment by bulgakovk** [comment]
Sure

**Comment by White1337** [comment]
Are u able to give me a tut for that too? :') sry but im srsly not that expirienced...

**Comment by bulgakovk** [comment]
It doesn't relate to bot issues.
