### ISSUE TITLE
configure problem.

### ISSUE THREAD

**Issue by gixek** [bulgakovk/steamBot#7]
Hello, how i can run it on mysql script? I don't see a configure of it.

**Comment by bulgakovk** [comment]
@gixek Can you explain what does "mysql script" mean?

**Comment by gixek** [comment]
My website is running on mysql.

**Comment by bulgakovk** [comment]
You need to require "mysql" package and define your configure. What's problem?

**Comment by gixek** [comment]
I know, i need package, but how to define it, and how to configure query and trade offerts

**Comment by bulgakovk** [comment]
>var mysql      = require('mysql');
var mysqlInfo;
mysqlInfo = {
  host     : '',
  user     : '',
  password : '',
  database : '',
  charset  : ''
};

**Comment by gixek** [comment]
And trade offerts etc. I can copy from old bot?

**Comment by bulgakovk** [comment]
You can use this [lib](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager).
